# Generated by Django 4.1.1 on 2022-09-20 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
        ('users', '0004_verificationcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connections',
            new_name='Connection',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='dateTime',
            new_name='creation_time',
        ),
    ]
