# Generated by Django 4.1.1 on 2022-09-20 18:05

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_connections_connection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=users.models.User.profile_pic_image_path),
        ),
    ]
