# Generated by Django 4.1.1 on 2022-09-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_connections_connection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
