# Generated by Django 4.1.1 on 2022-09-21 07:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail_pic',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=users.models.User.profile_pic_image_path),
        ),
    ]
