# Generated by Django 4.1.1 on 2022-09-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_connection_creation_time'),
        ('users', '0008_user_thumbnail_pic'),
    ]

    operations = [
    ]
